version: 0.0
os: linux

hooks:
  - event: ApplicationStop
    timeout: 300
    runas: root
    script: scripts/stop_container.sh

  - event: AfterInstall
    timeout: 300
    runas: root
    script: scripts/start_container.sh

